Arcyd: Separate out concise and verbose error logs
At all places where an error is logged, trigger two events - one with a
concise message to go into all logging handlers and another which has a
prefix 'VERBOSE MESSAGE' which is ignored by the info logs.

Test plan:
$ ./precommit.sh

Since this commit also changes the way exceptions are raised at a few
places, following is a test plan to ensure that those changes work
fine.

1. In py/abd/abdi_processrepoarglist.py - function do(), add the
following line just above the except block at line 146:
    raise phlsys_subprocess.CalledProcessError(external_report_command, None, None, None, 1, None)

Now run ./test_shell.sh. Ensure that the error log - ../var/log/error
contains the error messages similar to the following:
  ERROR: (MainProcess) External command: /home/username/phabricator-tools/testbed/arcyd/savereport failed with exception: CalledProcessError.
  ERROR: (MainProcess) VERBOSE MESSAGE: CycleReportJson:cmd: / h o m e / u s e r n a m e / p h a b r i c a t o r - t o o l s / t e s t b e d / a r c y d / s a v e r e p o r t
  stdout: None
  stderr: None

2. In abd/abdt_tryloop.py - function tryloop(), add the following line
just above the return statement on line 41:
  on_tryloop_exception(Exception(), None)

Now run ./test_shell.sh. Ensure that the error log - ../var/log/error
contains the error messages similar to the following:
  ERROR: (MainProcess) on_retry_exception: during "fetch-prune" encountered exception "Exception", will not retry. More detail: "origin".
  ERROR: (MainProcess) VERBOSE MESSAGE:
  None

3. In py/abd/abdi_processrepos.py - function _processrepolist(), add
the following line just above the except block at line 150:
  raise Exception()

Also, in py/abd/abdt_exhandlers.py - function
make_exception_message_handler(), add the following line as the first
line of the try block at line 70:
  raise Exception()

Now run ./test_shell.sh and exit the shell. When the test shell exits,
some info will be printed, ensure that it contains error messages
similar to the following:
  -- var/log/info --
  INFO: (MainProcess) arcyd started
  ERROR: (MainProcess) abdt_exhandlers: during "None" encountered exception "Exception", will retry in Arcyd will now stop.
  ERROR: (MainProcess) Encountered exception when sending mail
  INFO: (MainProcess) arcyd stopped